name: 🚀 Release FastAPI

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Publicar Release
    runs-on: ubuntu-latest
    permissions:
      contents: write       # para pushear commits y tags
      packages: write       # si publicas en Packages

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.10'
      
      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Configurar e instalar deps
        run: |
          poetry config virtualenvs.in-project true
          poetry install --with dev

      - name: Build distributions
        run: poetry build --format=wheel --format=sdist

      - name: Release con python-semantic-release Action
        uses: python-semantic-release/publish-action@v9.21.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
