name: 🚀 Release FastAPI

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Publicar Release
    runs-on: ubuntu-latest
    permissions:
      contents: write       # para pushear commits y tags
      packages: write       # si publicas en Packages

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.10'

      - name: Instalar Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Configurar Poetry
        run: |
          poetry config virtualenvs.in-project true
          poetry install --with dev

      - name: Ejecutar semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}  # opcional
        run: |
          poetry run release publish
